export const sample_foods: any[] = [
 {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'https://www.simplyrecipes.com/thmb/KE6iMblr3R2Db6oE8HdyVsFSj2A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-1024x682-583b275444104ef189d693a64df625da.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'https://www.flavcity.com/wp-content/uploads/2018/06/meatballs-tomato-sauce.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'https://vinpro.store/wp-content/uploads/2022/07/cach-lam-banh-Hamburger-5.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'https://natashaskitchen.com/wp-content/uploads/2012/07/Pan-Fried-Potatoes-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2023/10/Chicken-Soup-main-2.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRueq1yGWS16Ef3juKJRX7foCpEJ1k6MowJtA&s',
    tags: ['FastFood', 'Pizza', 'Lunch'],
    },
  {
    id:'7',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2023/10/Chicken-Soup-main-2.jpg',
    tags: ['SlowFood', 'Soup'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'Nam Huỳnh',
    email: 'nam@gmail.com',
    password: 'nam123456',
    address: 'Huế',
    isAdmin: true,
  },
  {
    name: 'Uyên Nguyễn',
    email: 'uyen@gmail.com',
    password: '12345',
    address: 'Huế',
    isAdmin: false,
    },
   {
    name: 'nhi Nguyễn',
    email: 'nhi@gmail.com',
    password: '12345',
    address: 'Đà Nẵng',
    isAdmin: false,
    },
    {
    name: 'Đức Huỳnh',
    email: 'duc@gmail.com',
    password: '12345',
    address: 'Quảng Nam',
    isAdmin: false,
    },
     {
    name: 'Hiền Huỳnh',
    email: 'hien@gmail.com',
    password: '12345',
    address: 'Đà Nẵng',
    isAdmin: false,
  }
];